trigger:
- master

pool:
  name: WindowVm

variables:
  # Define your Azure Container Registry information
  containerRegistry: 'azuredb2acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  imageName: 'biradarsandeepsamplejavaapp'
  tag: '$(Build.BuildId)'

jobs:
- job: Build
  displayName: Build and Push Docker Image
  steps:
  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      command: 'buildAndPush'
      repository: '$(containerRegistry)/$(imageName)'
      dockerfile: '$(dockerfilePath)'
      context: '$(Build.SourcesDirectory)'
      tags: |
        $(tag)
